unstructure:
  email:
    imap:
      host: imap.gmail.com
      port: 993
      username: alphaesaigenaitest@gmail.com
      password: zogmmeimuongraet
      use_ssl: true
      mailbox: INBOX
  gmail:
    credentials_path: /home/logi/txtai/etl_pipeline/unstructure/credentials.json
    token_path: /home/logi/txtai/etl_pipeline/unstructure/token.json
